### PR TITLE
44 Fix sadboi agent 😢🕵️🔀😄🕵️

### LINKED ISSUE #44: Fix sadboi 😢 agent 🕵️‍♂️

### PR DESCRIPTION
**Pull request by LoganParker**
closes #44 <3

### CODE REVIEW

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java [hunk 1]
```diff
@@ -123,38 +134,23 @@ private int playthrough(TreeNode current) {
...
-			// Check if the child has children or is a leaf
-			if (current.children.isEmpty())
-				leaves.add(current);
-			else
-				// Recursively add current's leaves to the list of leaves
-				leaves.addAll(getLeaves(current));
-		}
+			TreeNode nodetoexpand = null;
 
-		return leaves;
```
Comment (LoganParker) [inline team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: - Old getMaxLeaf was causing agent to commit suicide
- Recursion seems to be quite a bit slower (likely due to the increase in branching??)
- New method threw me a null exception VERY late in the game, there were still moves to be made, however, I had technically lost so I'm not sure if this is a real problem 
- Posted my spreadsheet in the discord

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java [hunk 2]
```diff
@@ -213,9 +214,9 @@ public AmazonsAction getAction() {
 
 		private double getUCB() {
 			// EXPLORATION_FACTOR = constant defined at the top of the class.
-			// If we hit 0, then the unvisited node should return infinity.
+			// If we hit 0, then the unvisited node should return the exploration factor.
 			if (this.getVisits() == 0) {
-				return Double.MAX_VALUE;
```
Comment (LoganParker) [inline team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: Returning infinity caused issues when selecting UCB

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java [hunk 3]
```diff
@@ -33,40 +33,42 @@
...
+			if (child == null) {
+				//unaccounted for terminal state here so we need to send back the results
+				backpropagate(current, current.state.getOpponent());
+				continue;
 			}
+
+			winner = playthrough(child);
+			backpropagate(child, winner);
+
 			count++;
```
Comment (LoganParker) [inline team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: - This seems to have been the cause of our MCTS only moving one agent at a time, we would pick one node and continue to explore it rather than exploring all nodes

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java [hunk 4]
```diff
@@ -33,40 +33,42 @@
...
 
 	public MonteCarloPlayer() {
-		super("jaden_mc", "montecarlo");
+		super("group1-mc", "montecarlo");
 	}
 
 	@Override
 	protected void onMoveReceived() {
 		AmazonsLocalBoard rootState = board.copy();
-		rootState.localPlayer = board.getOpponent();
```
Comment (LoganParker) [inline team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java:50]: - Caused our agent to move the opposing teams player, handled the initial reason for this in getBestMove

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java [hunk 5]
```diff
@@ -78,11 +80,20 @@ private TreeNode getBestMove(TreeNode root) {
...
 		for (TreeNode node : root.children) {
-			int wins = node.getWins();
+			/*
+			 * Flip the wins, we need opponent wins due to how the pattern of our tree works:
+			 * When the board is passed to us, the root will be OUR turn
+			 * the children will all be of the opponents turn
+			 * so in a sense we actually want the node that is ~losing~ the most
+			 */
+
+			int wins = node.getVisits() - node.getWins();
```
Comment (LoganParker) [inline team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: - @JadenBalogh see above my removal of line 50, not sure if you remember this conversation, but it turns out we do want to pass the root as our color and then leave the children node as the opposing turn, easier to explain over voice which I can do Sunday if you want, but it's essentially because the edge is the action itself and then the node corresponds to the game state so the edge is our action, and then the node will be the opposing teams game state to start with, so we essentially find how many losses for the opposing player

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java [hunk 6]
```diff
@@ -33,40 +33,42 @@
...
+			TreeNode child = current.expand();
+
+			if (child == null) {
+				//unaccounted for terminal state here so we need to send back the results
+				backpropagate(current, current.state.getOpponent());
+				continue;
 			}
+
+			winner = playthrough(child);
+			backpropagate(child, winner);
```
Comment (JadenBalogh) [inline team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: This is a much better approach to the core search loop. Thanks for refactoring this.

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java (hunk 5 above)
Comment (JadenBalogh) [inline team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java:85]: This change is a result of the way we are storing wins in Nodes. From Discord:

> Ok, so another confusion because of our Node representation is whether wins belong to the action (i.e. a "winning move" or "losing move" for the action that got us here) or whether they belong to the state (i.e. a "won game" or "lost game" for the current player). Because of our updated definition of localPlayer for the tree, these two are opposite definitions of a win: the action of a given node belongs to the localPlayer of the previous node.

> In Logan's PR, he makes it so that a Node's wins represent the number of games the player who is making the next move from the current state has won.

> Which is why he changes getBestMove() to calculate opponent wins instead, because the Nodes representing the possible next moves don't store whether that move is the best, they store whether the player making the next move did the best.

We should discuss as a team whether it makes more sense for wins to belong to the action or the state.

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java [hunk 7]
```diff
@@ -123,38 +134,23 @@ private int playthrough(TreeNode current) {
...
 
-		return leaves;
+			for (TreeNode child : node.children) {
+				double ucb = child.getUCB();
+				if (ucb > maxUCB) {
+					maxUCB = ucb;
+					nodetoexpand = child;
+				}
+			}
+			node = nodetoexpand;
```
Comment (JadenBalogh) [inline team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: This updated `getMaxLeaf()` is significantly more efficient from an algorithmic standpoint, *if it works*. It uses a greedy search to only explore nodes with the highest UCB value at a given depth, potentially skipping a large number of nodes at every iteration, reducing average complexity.

However, this approach operates under the assumption that every node has a UCB value that is greater than or equal to that of any of its children. Have you proven that this assumption is universally true?

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java [hunk 8]
```diff
@@ -195,8 +193,11 @@ public TreeNode expand() {
 				children.add(new TreeNode(childState, childAction, this));
 			}
 
-			// Return the first child expanded
-			return children.get(0);
+			// Return a random child expanded - If we choose only the first node, it will just go down one path.
+			// This is part of why it was just moving to the sad corner
+			int index = (int) (Math.random() * children.size());
```
Comment (JadenBalogh) [inline team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: I don't see how this affects our algorithm. This will only make a difference if the AI is unable to check all the nodes at the current depth - and that change will just mean picking randomly instead of only the first choice at the deepest part of the search. The only way this could possibly have an impact, is if we were to discover a heuristic which stated that in general, moves in certain regions of the board are more ideal than others - in which case, I would argue we should bias towards those locations rather than using randomness anyway.

That all said, I don't mind the change. While it's effectively meaningless, having the AI pick randomly will make it feel more like a real decision if the AI does not manage to search the tree to a meaningful depth.

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java (hunk 7 above)
Comment (JadenBalogh) [reply team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: For what it's worth, I think you are most likely correct in this assumption. Looking over John Levine's video, I believe he uses the same heuristic in his approach.

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java [hunk 9]
```diff
@@ -213,9 +214,9 @@ public AmazonsAction getAction() {
 
 		private double getUCB() {
 			// EXPLORATION_FACTOR = constant defined at the top of the class.
-			// If we hit 0, then the unvisited node should return infinity.
+			// If we hit 0, then the unvisited node should return the exploration factor.
 			if (this.getVisits() == 0) {
-				return Double.MAX_VALUE;
+				return EXPLORATION_FACTOR;
```
Comment (JadenBalogh) [inline team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: This contradicts my primary source for the MCTS algorithm (John Levine's video linked at the top). I would love to read your source(s) which state this as a possible alternative UCB calculation.

**Review by JadenBalogh — COMMENTED** [review]
Awesome work with these changes. I've added some comments, elaborations and questions below. Will wait for team review before approving.

Also, some formatting and naming should be updated, but this review only covers the algorithm changes, not the code itself.

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java (hunk 9 above)
Comment (LoganParker) [reply team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: I think you're technically right here, when I was doing my initial implementation for the research steps I was looking at a lot of different implementations for different games, and a few seemed to use this method, but a standard ucb calculation will return infinity. I changed this because returning infinity throws an error, and returning this gave me a working player. We can change this if we want, but it works and we need a working agent for Monday, so maybe not a priority just yet

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java (hunk 7 above)
Comment (LoganParker) [reply team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: Yes so my understanding is that the parent node should have a UCB that is at least equal to the best node in its children, as when we backpropagate, the wins we backpropagate are added to the parent node resulting in a UCB being greater than or equal to that of any of its children

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java (hunk 5 above)
Comment (LoganParker) [reply team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java:85]: Was this discussed during the meeting? I personally think the way it's implemented currently although being slightly difficult to read code - wise does make a lot of sense to me

Comment (JadenBalogh) [reply team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java:85]: Yeah, we discussed this in the meeting yesterday and agreed that this way seems like a reasonable implementation.

File: team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java (hunk 7 above)
Comment (JadenBalogh) [reply team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: Did you find any evidence to support this? We were struggling to justify the validity of this approach in yesterday's meeting. For example, just because a parent node has the greatest value among its siblings might not necessarily imply that it contains the greatest leaf node as well. For example, this winning parent node may be made of many average children nodes below it, whereas another parent node with slightly less total UCB might have one standout child with the highest actual UCB value of any leaf.

Comment (LoganParker) [reply team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: I would think that you would want to visit subtrees with higher average UCT rather than visit subtrees with the potential to have 1 high UCT value because a higher average value means it's got better positioning than a node with one really high uct. If a case occurs where the move with the very high UCT is blocked by another move, we would still want to make a move that still results in a good outcome overall.

Comment (JadenBalogh) [reply team-01/src/main/java/ubc/cosc322/MonteCarloPlayer.java]: The premise of it seems reasonable. I'm not opposed to doing it that way - it just means we're using a heuristic to prioritize leaves, rather than solely relying on the max UCB. It may end up being stronger to do it this way anyway (and certainly, the function is algorithmically more efficient).

**Review by JadenBalogh — APPROVED** [review]
I've made some formatting and minor changes but otherwise this looks good. I changed the UCB to use infinity again and had no issues when playing through a full game. Through testing, the AI does sometimes error towards the end of the game as described in Discord, but otherwise seems to play properly, albeit poorly.
